# Generated by Django 2.0.7 on 2021-08-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('history', 'history'), ('science', 'science'), ('english', 'english'), ('math', 'math')], max_length=60),
        ),
    ]
