# Generated by Django 2.0.7 on 2021-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_auto_20210827_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('math', 'math'), ('history', 'history'), ('science', 'science'), ('english', 'english')], max_length=60),
        ),
    ]
