# Generated by Django 2.0.7 on 2021-08-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20210828_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('history', 'history'), ('science', 'science'), ('math', 'math'), ('english', 'english')], max_length=60),
        ),
    ]
