# Generated by Django 2.1.5 on 2021-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0005_auto_20210828_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='title',
            field=models.CharField(choices=[('history', 'history'), ('math', 'math'), ('science', 'science'), ('english', 'english')], max_length=60),
        ),
    ]
